//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PENALTIES
    {
        public int ID { get; set; }
        public string UserTCKN { get; set; }
        public Nullable<int> LicensePlateID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual TBL_LPLATES TBL_LPLATES { get; set; }
    }
}
