//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LPLATES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LPLATES()
        {
            this.TBL_PENALTIES = new HashSet<TBL_PENALTIES>();
        }
    
        public int ID { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual TBL_USERS TBL_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PENALTIES> TBL_PENALTIES { get; set; }
    }
}
